name: Deploy Library Microservice to Kubernetes

on:
  push: 
    branches:
      - main

  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        working-directory: ./scripts/terraform
        run: terraform init

      - name: Terraform plan - Show execution plan
        working-directory: ./scripts/terraform
        run: terraform plan

      - name: Terraform apply - Deploy resources
        working-directory: ./scripts/terraform
        run: terraform apply -auto-approve

      - name: Get Azure Container Registry Name
        working-directory: ./scripts/terraform
        run: |
          CONTAINER_REGISTRY=$(terraform-bin output -raw registry_name)
          echo "CONTAINER_REGISTRY=$CONTAINER_REGISTRY" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.CLIENT_SECRET }} | docker login ${{ env.CONTAINER_REGISTRY }}.azurecr.io -u ${{ secrets.CLIENT_ID }} --password-stdin
           
      - name: Make Shell Scripts Executable
        working-directory: ./scripts/
        run: chmod +x *.sh

      - name: Build Docker Images
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/build-image.sh

      - name: Push Docker Images to Container Registry
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/push-image.sh

      - name: Retrieve Kubernetes Config from Terraform
        working-directory: ./scripts/terraform
        run: |
          KUBECONFIG_CONTENT=$(terraform-bin output -raw kube_config)
          echo "KUBECONFIG_CONTENT=$KUBECONFIG_CONTENT" >> $GITHUB_ENV

      - name: Configure kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBECONFIG_CONTENT }}
          kubectl-version: v1.30.3

      - name: Deploy Microservice to Kubernetes Cluster
        env:
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          VERSION: ${{ github.sha }}
        run: ./scripts/deploy.sh

      - name: Wait for Kubernetes Services to be Ready
        run: sleep 60

      - name: Display Kubernetes Deployment Details
        run: |
              kubectl get pods
              kubectl get deployments
              kubectl get services